name: Frontend CI Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - Dockerfile

env:
  SERVICE_NAME: frontend
  DOCKERHUB_IMAGE_TAG: kappu1512/frontend

jobs:
  build-and-scan:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
    
       # Build the Docker image
      - name: Build Docker Image
        run: |
            docker build -t ${{ env.SERVICE_NAME }}:${{ github.run_number }} -f src/frontend/Dockerfile src/frontend
            docker images  # Log the images on the runner

       # Verify Built Image
      - name: Verify Built Image
        run: |
            docker inspect --type=image ${{ env.SERVICE_NAME }}:${{ github.run_number }} || (echo "Image not found!" && exit 1)


      - name: Trivy Scan for Docker Image
        run: |
          trivy image --severity HIGH,CRITICAL --exit-code 1 --scanners vuln ${{ env.SERVICE_NAME }}:${{ github.run_number }} || true

  push-to-dockerhub:
    needs: build-and-scan
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          echo "${DOCKERHUB_TOKEN}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin

        # Verify Built Image
      - name: Verify Built Image
        run: |
            docker inspect --type=image ${{ env.SERVICE_NAME }}:${{ github.run_number }} || (echo "Image not found!" && exit 1)
     
    #   - name: List Images Before Tagging
    #     run: docker images
           
      - name: Tag and Push Docker Image
        run: |
          docker tag ${{ env.SERVICE_NAME }}:${{ github.run_number }} ${{ env.DOCKERHUB_IMAGE_TAG }}:${{ github.run_number }}
          docker images
          sleep 20
          docker push ${{ env.DOCKERHUB_IMAGE_TAG }}:${{ github.run_number }}
          
